import type { Metadata } from "next";
import { Inter, Handlee } from "next/font/google";
import { BackgroundSimple } from "@/components/ui/background-simple";
import Navbar from "@/components/Navbar";
import { Providers } from "@/components/providers";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
const handlee = Handlee({
  variable: "--font-handlee",
  subsets: ["latin"],
  weight: ["400"]
})


export const metadata: Metadata = {
  title: "Hello",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${handlee.variable} antialiased bg-background`}
      >
        <Providers>
        <div className="fixed inset-0 -z-10 hidden sm:flex">
          <BackgroundSimple />
        </div>
          <header className="fixed top-0 left-0 w-full z-20">
            <Navbar />
          </header>
        <main className="pt-[20px] pb-[60px] h-full overflow-y-auto">
          {children}
        </main>
            <footer className="fixed bottom-0 left-0 w-full z-10 bg-background hidden sm:flex justify-center py-2">
              <p className="text-sm text-foreground">© 2025 Shiro. All rights reserved.</p>
            </footer>
        </Providers>
      </body>
    </html>
  );
}
