import type { Metadata } from "next";
import { Inter, Handlee } from "next/font/google";
import { BackgroundBeams } from "@/components/ui/background-beams";
import Navbar from "./components/Navbar";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});
const handlee = Handlee({
  variable: "--font-handlee",
  subsets: ["latin"],
  weight: ["400"]
})


export const metadata: Metadata = {
  title: "Hello",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${handlee.variable} antialiased bg-neutral-950`}
      >
        <header className="absolute top-0 left-0 w-full z-20">
          <Navbar />
        </header> 
        <main>
          {children}
          <BackgroundBeams />
        </main>
        <footer className="hidden sm:flex bg-neutral-950">
          <p className="text-sm text-white">© 2025 Shiro. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
